### ISSUE TITLE
Close window on issuance of second command

### ISSUE THREAD

**Issue by jgbishop** [jgbishop/sxs-settings#1]
If the `sxs_settings` or `sxs_key_bindings` command has already been issued, the window it created is open, and the command is issued again, it would be nice to close the window that we opened the first time around. This would especially be handy when bound to a key.

**Comment by thecodechef** [comment]
Wouldn't it be possible to solve this with sublime_plugin.EventListener

**Comment by thecodechef** [comment]
Something like this or something like it 


def closeWindow(self):
	close_window = sublime.active_window()
	close_window.run_command("close_window")

class sxsSettingsCommand(sublime_plugin.WindowCommand):
	def run(self):
		openWindow(self.window, "settings", getSetting('display_using_rows', PREF_USE_ROWS_DEFAULT))

class sxsSettings(sublime_plugin.EventListener):
	def on_new(self):
		closeWindow(self.window)

**Comment by thecodechef** [comment]
Something Like this

``` python
def closeWindow(self):
    close_window = sublime.active_window()
    close_window.run_command("close_window")
class sxsSettingsCommand(sublime_plugin.WindowCommand):
    def run(self):
        openWindow(self.window, "settings", getSetting('display_using_rows', PREF_USE_ROWS_DEFAULT))

class sxsSettings(sublime_plugin.EventListener):
    def on_new(self):
        closeWindow(self.window)
```
