### ISSUE TITLE
Side-by-Side not working on new build

### ISSUE THREAD

**Issue by amontevl** [jgbishop/sxs-settings#13]
Just installed the new build 3143 and Side-by-Side is not working correctly

**Comment by jgbishop** [comment]
It seems to work for me just fine in 3144. Have you tried that build?

**Comment by jgbishop** [comment]
I also just tried in 3143 (on a separate system), and things also seem to work. I'm going to close this for now; if you continue having issues, feel free to reopen with the following information:

* Operating system
* Any errors or warnings you see in the Sublime Text console
* Any other error messages you are encountering
