### ISSUE TITLE
Only list keymap files matching to platform

### ISSUE THREAD

**Issue by pykong** [jgbishop/sxs-settings#15]
First of all thanks for putting up this neat plugin. It really fills a void, left by ST's native UI.

What I'd like to see is an automatic prefiltering hiding those keymap files not relevant to the current OS.
Thereby it would remove much cruft from the quick panel making finding keymaps quicker.

It is a small but powerful improvement I think.

**Comment by jgbishop** [comment]
This is a great idea! I'll try to get it implemented soon.

**Comment by jgbishop** [comment]
Implemented in 1.5.0, which I've just pushed out! Thanks for the great suggestion.

**Comment by pykong** [comment]
Wow. That was a fast turnaround time. You are awesome!

**Comment by jgbishop** [comment]
You caught me on a good day. 😄

Thanks again!
