### ISSUE TITLE
Remove Redundant Commands

### ISSUE THREAD

**Issue by pykong** [jgbishop/sxs-settings#16]
The commands `sxs_settings` and `sxs_keybindings` are both redundant as of ST v3157.
Sublime provides two commands that provide the exact functionality (see screenshots below).

![selection_007](https://user-images.githubusercontent.com/20211140/36995527-8f270efe-20b4-11e8-8fe0-0a0f3e65b62b.jpg)
![selection_008](https://user-images.githubusercontent.com/20211140/36995538-948c6204-20b4-11e8-84ed-a06ccf641ed0.jpg)

Maybe the package can be rectified to only provide the single `sxs_select_file` command.
The underlying method could be extended to take an argument to prepopulate the input field.

Predefined keybindings to that command with the args: `".sublime-settings"` and `".sublime-keymap"` could be provided for convenience.

Thereby the user interface could be simplified and be made more consistent.
Sublime Text's fuzzy search is super powerful, we should embrace it!

**Comment by jgbishop** [comment]
Yes, the internals of this plugin could be considerably simplified. There's actually a new internal command for opening the settings window, though I'm not 100% sure if I would then have control over said window if I used it. I'll have to dig in and take a look.

**Comment by pykong** [comment]
Great! In case you need a second opinion or hand in something to make this awesome little plugin even greater: Just summon me.

**Comment by jgbishop** [comment]
The upcoming 1.6.0 release will use the new edit_settings machinery underneath to open files. This simplifies the code considerably.

I'm leaving the two command palette commands in for now, however, for backwards compatibility.
