### ISSUE TITLE
Keymap Issue!!!

### ISSUE THREAD

**Issue by thecodechef** [jgbishop/sxs-settings#9]
Hey just thought you should know that ctrl+s is being used by save on st2 & st3 keymaps and can you add a way to get the keymap setting in main.sublime-menu that people can get change the keymaps if they conflicting problems too plz & thx for all the hard work

**Comment by jgbishop** [comment]
The default key binding is Ctrl+K, followed by Ctrl+S (it's a key chord). As for the extra menu items in the packages menu, that's a good idea (though, with this plug-in installed, the menu items become somewhat of a moot point).

**Comment by thecodechef** [comment]
ok thank you

**Comment by thecodechef** [comment]
yep just tried it thank you so much for explaining it for me
